/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/
#include<iostream>

class Solution {
public:
    char findTheDifference(string s, string t) {
        int n=s.size();
        int sum_s=0,sum_t=0;
        for(int i=0;i<n;i++){
            sum_s+=s[i];
            sum_t+=t[i];
        }
        sum_t+=t[n];
        return char(sum_t-sum_s);
    }
};
